// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2nycQlQA4r0PccX-8jl58mLzxc2StZzU',
    appId: '1:964857942111:web:288b809e86dc27521c4bea',
    messagingSenderId: '964857942111',
    projectId: 'socialmediapp-f4d36',
    authDomain: 'socialmediapp-f4d36.firebaseapp.com',
    storageBucket: 'socialmediapp-f4d36.appspot.com',
    measurementId: 'G-WEG6C65BP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbhaoL3BuIUJnD9xViL4sYvSmUPSulNWg',
    appId: '1:964857942111:android:864a218dca186fb21c4bea',
    messagingSenderId: '964857942111',
    projectId: 'socialmediapp-f4d36',
    storageBucket: 'socialmediapp-f4d36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWTlxVZw-NK8WEgz_kWlpPM--OksPjKK0',
    appId: '1:964857942111:ios:a6261e8405ab80071c4bea',
    messagingSenderId: '964857942111',
    projectId: 'socialmediapp-f4d36',
    storageBucket: 'socialmediapp-f4d36.appspot.com',
    iosBundleId: 'com.example.socialmediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWTlxVZw-NK8WEgz_kWlpPM--OksPjKK0',
    appId: '1:964857942111:ios:2d174c2c4c9192481c4bea',
    messagingSenderId: '964857942111',
    projectId: 'socialmediapp-f4d36',
    storageBucket: 'socialmediapp-f4d36.appspot.com',
    iosBundleId: 'com.example.socialmediaApp.RunnerTests',
  );
}
